spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nurspace_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: ${DB_USER}
    password: ${DB_PASSWD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
    hibernate:
      ddl-auto: update

  #thymeleaf:
    #cache: false
    #check-template-location: true
    #prefix: classpath:/templates/
    #suffix: .html
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:src/main/resources/static/
  h2:
    console:
      enabled: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: nurspace-bucket
      
server:
  servlet:
    session:
      cookie:
        http-only: false